apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: kwamasco/basicmonitoringapp4k8s:v1
        ports:
        - containerPort: 8000

